# create your drupal and postgres config here, based off the last assignment
version: '2'

services:
  nginx:
    image: dockerized-react-site
    build:
      context: .
      dockerfile: Dockerfile
